import { splitAddressHeader } from './contacts.js';
import { normalizeOverrideKey, resolveOverride } from './priority.js';
import { getMailDb, recomputeThread, readMeta, writeMeta } from './store.js';

export const INBOX_CATEGORIES = ['primary', 'social', 'other'];

export const STRONG_CATEGORY_SOURCES = new Set([
  'user',
  'override',
  'social-domain',
  'contact',
  'bulk-headers',
]);

export const SOCIAL_DOMAINS = [
  'linkedin.com',
  'facebookmail.com',
  'facebook.com',
  'meta.com',
  'x.com',
  'twitter.com',
  'instagram.com',
  'reddit.com',
  'youtube.com',
  'discord.com',
  'nextdoor.com',
  'meetup.com',
  'pinterest.com',
  'tiktok.com',
  'threads.net',
  'substack.com',
  'medium.com',
];

const CATEGORY_RANK = { primary: 3, social: 2, other: 1 };

/**
 * @param {unknown} value
 * @returns {value is 'primary' | 'social' | 'other'}
 */
export function isInboxCategory(value) {
  return INBOX_CATEGORIES.includes(String(value ?? '').toLowerCase());
}

/**
 * @param {string} domain
 */
export function isSocialDomain(domain) {
  const bare = String(domain ?? '')
    .trim()
    .toLowerCase()
    .replace(/^\.+/, '');
  if (!bare) return false;
  return SOCIAL_DOMAINS.some((seed) => bare === seed || bare.endsWith(`.${seed}`));
}

/**
 * @param {Map<string, unknown> | Record<string, unknown> | null | undefined} headers
 */
export function deriveBulkSignals(headers) {
  const empty = {
    listUnsubscribe: false,
    listId: false,
    precedenceBulk: false,
    autoGenerated: false,
  };
  if (!headers) return empty;

  const read = (name) => {
    if (typeof headers.get === 'function') {
      return headers.get(name);
    }
    return headers[name] ?? headers[name.toLowerCase()];
  };

  const listUnsubscribe = Boolean(read('list-unsubscribe'));
  const listId = Boolean(read('list-id'));
  const precedence = String(read('precedence') ?? '')
    .trim()
    .toLowerCase();
  const precedenceBulk = /^(bulk|list|junk)$/.test(precedence);
  const autoSubmitted = String(read('auto-submitted') ?? '')
    .trim()
    .toLowerCase();
  const autoGenerated = Boolean(autoSubmitted && autoSubmitted !== 'no');

  return { listUnsubscribe, listId, precedenceBulk, autoGenerated };
}

/**
 * @param {{ listUnsubscribe?: boolean, listId?: boolean, precedenceBulk?: boolean, autoGenerated?: boolean } | null | undefined} sig
 */
export function isBulk(sig) {
  if (!sig) return false;
  return Boolean(sig.listUnsubscribe || sig.listId || sig.precedenceBulk || sig.autoGenerated);
}

/**
 * @param {{ categoryOverride?: string, senderOverride?: string, fromDomain?: string, repliedCount?: number, bulkSignals?: ReturnType<typeof deriveBulkSignals> | null, aiBucket?: string, triage?: { bucket?: string, category?: string } | null, }} input
 * @returns {{ category: 'primary' | 'social' | 'other', source: string }}
 */
export function classifyCategory(input = {}) {
  const pin = String(input.categoryOverride ?? '').toLowerCase();
  if (isInboxCategory(pin)) {
    return { category: pin, source: 'user' };
  }

  if (String(input.senderOverride ?? '').toLowerCase() === 'high') {
    return { category: 'primary', source: 'override' };
  }

  if (isSocialDomain(input.fromDomain ?? '')) {
    return { category: 'social', source: 'social-domain' };
  }

  if ((Number(input.repliedCount) || 0) > 0) {
    return { category: 'primary', source: 'contact' };
  }

  if (isBulk(input.bulkSignals)) {
    return { category: 'other', source: 'bulk-headers' };
  }

  const aiBucket = String(input.aiBucket ?? input.triage?.bucket ?? '').toLowerCase();
  if (isInboxCategory(aiBucket)) {
    return { category: aiBucket, source: 'ai-bucket' };
  }

  const triageCat = String(input.triage?.category ?? '').toLowerCase();
  if (['newsletter', 'notification', 'receipt'].includes(triageCat)) {
    return { category: 'other', source: 'triage-category' };
  }
  if (['needs_reply', 'calendar', 'security'].includes(triageCat)) {
    return { category: 'primary', source: 'triage-category' };
  }

  return { category: 'primary', source: 'default' };
}

/**
 * @param {Iterable<string>} categories
 */
export function rollupThreadCategory(categories) {
  let best = '';
  let bestRank = 0;
  for (const raw of categories) {
    const cat = String(raw ?? '').toLowerCase();
    const rank = CATEGORY_RANK[cat] ?? 0;
    if (rank > bestRank) {
      bestRank = rank;
      best = cat;
    }
  }
  return best;
}

/**
 * @param {Map<string, string>} overrides
 * @param {string} address
 */
export function resolveCategoryOverride(overrides, address) {
  return resolveOverride(overrides, address);
}

/**
 * @param {import('better-sqlite3').Database} db
 * @param {string} fromHeader
 */
export function loadCategorySignalsForAddress(db, fromHeader) {
  const { address } = splitAddressHeader(String(fromHeader ?? ''));
  const at = address.indexOf('@');
  const fromDomain = at >= 0 ? address.slice(at + 1) : '';

  let repliedCount = 0;
  if (address.includes('@')) {
    const row = db.prepare('SELECT replied_count FROM contacts WHERE address = ?').get(address);
    repliedCount = Number(row?.replied_count) || 0;
  }

  /** @type {Map<string, string>} */
  const categoryOverrides = new Map();
  try {
    for (const row of db.prepare('SELECT sender, category FROM sender_category_overrides').all()) {
      categoryOverrides.set(row.sender, row.category);
    }
  } catch {
  }

  /** @type {Map<string, string>} */
  const priorityOverrides = new Map();
  for (const row of db.prepare('SELECT sender, level FROM sender_overrides').all()) {
    priorityOverrides.set(row.sender, row.level);
  }

  return {
    fromDomain,
    repliedCount,
    override: resolveCategoryOverride(categoryOverrides, address),
    senderOverride: resolveOverride(priorityOverrides, address),
  };
}

/**
 * @param {import('better-sqlite3').Database} db
 * @param {number} rowId
 * @param {{ fromHeader?: string, bulkSignals?: ReturnType<typeof deriveBulkSignals> | null, triage?: { bucket?: string, category?: string } | null, categoryOverride?: string, force?: boolean, }} [options]
 * @returns {{ category: string, source: string } | null}
 */
export function applyMessageCategory(db, rowId, options = {}) {
  const id = Number(rowId);
  if (!Number.isFinite(id)) return null;

  const existing = db
    .prepare('SELECT category, category_source, from_addr, triage_json FROM messages WHERE message_row_id = ?')
    .get(id);
  if (!existing) return null;

  if (!options.force && existing.category_source === 'user') {
    return { category: existing.category || 'primary', source: 'user' };
  }

  const fromHeader = String(options.fromHeader ?? existing.from_addr ?? '');
  const signals = loadCategorySignalsForAddress(db, fromHeader);

  let triage = options.triage ?? null;
  if (!triage && existing.triage_json) {
    try {
      triage = JSON.parse(existing.triage_json);
    } catch {
      triage = null;
    }
  }

  const result = classifyCategory({
    categoryOverride: options.categoryOverride ?? signals.override,
    senderOverride: signals.senderOverride,
    fromDomain: signals.fromDomain,
    repliedCount: signals.repliedCount,
    bulkSignals: options.bulkSignals ?? null,
    triage,
  });

  db.prepare(
    'UPDATE messages SET category = ?, category_source = ? WHERE message_row_id = ?',
  ).run(result.category, result.source, id);

  return result;
}

/**
 * @param {string} accountId
 * @param {string} messageKey
 * @param {string} aiBucket
 */
export async function reclassifyWithAiBucket(accountId, messageKey, aiBucket) {
  if (!isInboxCategory(aiBucket)) return null;

  const db = getMailDb(accountId);
  const needle = String(messageKey ?? '');
  if (!needle) return null;

  const row =
    db.prepare('SELECT message_row_id, thread_id, category_source, from_addr, triage_json FROM messages WHERE id = ?').get(
      needle,
    ) ??
    (() => {
      const colonAt = needle.lastIndexOf(':');
      if (colonAt <= 0) return null;
      return db
        .prepare(
          'SELECT message_row_id, thread_id, category_source, from_addr, triage_json FROM messages WHERE folder = ? AND uid = ?',
        )
        .get(needle.slice(0, colonAt), needle.slice(colonAt + 1));
    })();

  if (!row) return null;
  if (STRONG_CATEGORY_SOURCES.has(String(row.category_source ?? ''))) {
    return null;
  }

  let triage = null;
  if (row.triage_json) {
    try {
      triage = JSON.parse(row.triage_json);
    } catch {
      triage = null;
    }
  }
  triage = { ...(triage && typeof triage === 'object' ? triage : {}), bucket: String(aiBucket).toLowerCase() };

  const result = applyMessageCategory(db, row.message_row_id, {
    fromHeader: row.from_addr,
    bulkSignals: null,
    triage,
  });
  recomputeThread(db, row.thread_id);
  return result;
}

/**
 * @param {string} accountId
 */
export async function backfillCategoriesIfNeeded(accountId) {
  const db = getMailDb(accountId);
  if (readMeta(db, 'categoryBackfillAt', null)) {
    return { skipped: true, updated: 0 };
  }

  const rows = db
    .prepare(
      `SELECT message_row_id, thread_id, from_addr, triage_json
       FROM messages WHERE category = '' OR category IS NULL`,
    )
    .all();

  /** @type {Set<string>} */
  const threadIds = new Set();
  const apply = db.transaction(() => {
    for (const row of rows) {
      let triage = null;
      if (row.triage_json) {
        try {
          triage = JSON.parse(row.triage_json);
        } catch {
          triage = null;
        }
      }
      applyMessageCategory(db, row.message_row_id, {
        fromHeader: row.from_addr,
        bulkSignals: null,
        triage,
      });
      if (row.thread_id) threadIds.add(row.thread_id);
    }
    for (const threadId of threadIds) {
      recomputeThread(db, threadId);
    }
    writeMeta(db, 'categoryBackfillAt', new Date().toISOString());
  });
  apply();

  return { skipped: false, updated: rows.length };
}

/**
 * @param {string} accountId
 * @param {string} sender
 * @param {'primary' | 'social' | 'other' | ''} category
 */
export async function setCategoryOverride(accountId, sender, category) {
  const key = normalizeOverrideKey(sender);
  if (!key) {
    throw new Error('sender must be an email address or @domain');
  }
  const normalized = String(category ?? '').toLowerCase();
  if (normalized && !isInboxCategory(normalized)) {
    throw new Error('category must be "primary", "social", "other", or "" to clear');
  }

  const db = getMailDb(accountId);
  if (!normalized) {
    db.prepare('DELETE FROM sender_category_overrides WHERE sender = ?').run(key);
    return { sender: key, category: '' };
  }
  db.prepare(
    `INSERT INTO sender_category_overrides (sender, category, created_at) VALUES (?, ?, ?)
     ON CONFLICT(sender) DO UPDATE SET category = excluded.category, created_at = excluded.created_at`,
  ).run(key, normalized, new Date().toISOString());
  return { sender: key, category: normalized };
}

/**
 * @param {string} accountId
 * @param {string} sender
 */
export async function reclassifySenderMessages(accountId, sender) {
  const key = normalizeOverrideKey(sender);
  if (!key) return { updated: 0 };

  const db = getMailDb(accountId);
  const address = key.startsWith('@') ? null : key;
  const domain = key.startsWith('@') ? key.slice(1) : key.includes('@') ? key.slice(key.indexOf('@') + 1) : '';

  let rows;
  if (address) {
    rows = db
      .prepare(
        `SELECT message_row_id, thread_id, from_addr, triage_json, category_source
         FROM messages WHERE lower(from_addr) LIKE ?`,
      )
      .all(`%${address}%`);
    rows = rows.filter((row) => splitAddressHeader(row.from_addr).address === address);
  } else if (domain) {
    rows = db
      .prepare(
        `SELECT message_row_id, thread_id, from_addr, triage_json, category_source
         FROM messages WHERE lower(from_addr) LIKE ?`,
      )
      .all(`%@${domain}%`);
    rows = rows.filter((row) => {
      const addr = splitAddressHeader(row.from_addr).address;
      return addr.endsWith(`@${domain}`);
    });
  } else {
    return { updated: 0 };
  }

  /** @type {Set<string>} */
  const threadIds = new Set();
  let updated = 0;
  const tx = db.transaction(() => {
    for (const row of rows) {
      if (row.category_source === 'user') continue;
      let triage = null;
      if (row.triage_json) {
        try {
          triage = JSON.parse(row.triage_json);
        } catch {
          triage = null;
        }
      }
      applyMessageCategory(db, row.message_row_id, {
        fromHeader: row.from_addr,
        bulkSignals: null,
        triage,
      });
      updated += 1;
      if (row.thread_id) threadIds.add(row.thread_id);
    }
    for (const threadId of threadIds) {
      recomputeThread(db, threadId);
    }
  });
  tx();
  return { updated };
}

/**
 * @param {string} accountId
 * @param {string} threadId
 * @param {'primary' | 'social' | 'other'} category
 * @param {{ rememberSender?: boolean, sender?: string }} [options]
 */
export async function setThreadCategory(accountId, threadId, category, options = {}) {
  if (!isInboxCategory(category)) {
    throw new Error('category must be "primary", "social", or "other"');
  }
  const id = String(threadId ?? '');
  if (!id) {
    throw new Error('threadId is required');
  }

  const db = getMailDb(accountId);
  const rows = db
    .prepare('SELECT message_row_id, from_addr FROM messages WHERE thread_id = ? ORDER BY date_ms DESC')
    .all(id);
  if (!rows.length) {
    throw new Error('Thread not found');
  }

  const tx = db.transaction(() => {
    for (const row of rows) {
      db.prepare(
        'UPDATE messages SET category = ?, category_source = ? WHERE message_row_id = ?',
      ).run(String(category).toLowerCase(), 'user', row.message_row_id);
    }
    recomputeThread(db, id);
  });
  tx();

  let override = null;
  if (options.rememberSender) {
    const sender = String(options.sender ?? rows[0]?.from_addr ?? '');
    override = await setCategoryOverride(accountId, sender, category);
    await reclassifySenderMessages(accountId, override.sender);
  }

  return { threadId: id, category: String(category).toLowerCase(), override };
}
