/**
 * Inbox category classifier — pure precedence table + social suffix matching.
 */

import assert from 'node:assert/strict';
import { describe, test } from 'node:test';
import {
  classifyCategory,
  deriveBulkSignals,
  isBulk,
  isSocialDomain,
  rollupThreadCategory,
} from '../../server/email/categorize.js';

describe('isSocialDomain', () => {
  test('matches seed domains and subdomains', () => {
    assert.equal(isSocialDomain('linkedin.com'), true);
    assert.equal(isSocialDomain('e.linkedin.com'), true);
    assert.equal(isSocialDomain('mail.facebookmail.com'), true);
    assert.equal(isSocialDomain('example.com'), false);
    assert.equal(isSocialDomain('notlinkedin.com'), false);
  });
});

describe('deriveBulkSignals / isBulk', () => {
  test('reads list and precedence headers from a Map', () => {
    const headers = new Map([
      ['list-unsubscribe', '<mailto:u@example.com>'],
      ['precedence', 'bulk'],
    ]);
    const sig = deriveBulkSignals(headers);
    assert.equal(sig.listUnsubscribe, true);
    assert.equal(sig.listId, false);
    assert.equal(sig.precedenceBulk, true);
    assert.equal(isBulk(sig), true);
  });

  test('treats Auto-Submitted: no as non-bulk', () => {
    const headers = new Map([['auto-submitted', 'no']]);
    assert.equal(isBulk(deriveBulkSignals(headers)), false);
  });
});

describe('classifyCategory precedence', () => {
  test('user pin wins over everything', () => {
    const result = classifyCategory({
      categoryOverride: 'other',
      senderOverride: 'high',
      fromDomain: 'linkedin.com',
      repliedCount: 5,
      bulkSignals: { listUnsubscribe: true },
      aiBucket: 'primary',
    });
    assert.deepEqual(result, { category: 'other', source: 'user' });
  });

  test('priority high override beats social', () => {
    const result = classifyCategory({
      senderOverride: 'high',
      fromDomain: 'linkedin.com',
    });
    assert.deepEqual(result, { category: 'primary', source: 'override' });
  });

  test('social domain beats bulk headers', () => {
    const result = classifyCategory({
      fromDomain: 'e.linkedin.com',
      bulkSignals: {
        listUnsubscribe: true,
        listId: true,
        precedenceBulk: false,
        autoGenerated: false,
      },
    });
    assert.deepEqual(result, { category: 'social', source: 'social-domain' });
  });

  test('replied contact beats bulk headers', () => {
    const result = classifyCategory({
      fromDomain: 'shop.example.com',
      repliedCount: 2,
      bulkSignals: { listUnsubscribe: true, listId: false, precedenceBulk: false, autoGenerated: false },
    });
    assert.deepEqual(result, { category: 'primary', source: 'contact' });
  });

  test('bulk headers classify as other', () => {
    const result = classifyCategory({
      fromDomain: 'news.example.com',
      bulkSignals: {
        listUnsubscribe: true,
        listId: false,
        precedenceBulk: false,
        autoGenerated: false,
      },
    });
    assert.deepEqual(result, { category: 'other', source: 'bulk-headers' });
  });

  test('AI bucket only when ambiguous', () => {
    const result = classifyCategory({
      fromDomain: 'friend.example.com',
      aiBucket: 'social',
    });
    assert.deepEqual(result, { category: 'social', source: 'ai-bucket' });
  });

  test('AI bucket ignored when bulk already decided', () => {
    const result = classifyCategory({
      fromDomain: 'news.example.com',
      bulkSignals: {
        listId: true,
        listUnsubscribe: false,
        precedenceBulk: false,
        autoGenerated: false,
      },
      aiBucket: 'primary',
    });
    assert.deepEqual(result, { category: 'other', source: 'bulk-headers' });
  });

  test('triage category fallback maps newsletter → other', () => {
    const result = classifyCategory({
      fromDomain: 'brand.example.com',
      triage: { category: 'newsletter' },
    });
    assert.deepEqual(result, { category: 'other', source: 'triage-category' });
  });

  test('triage category fallback maps needs_reply → primary', () => {
    const result = classifyCategory({
      fromDomain: 'brand.example.com',
      triage: { category: 'needs_reply' },
    });
    assert.deepEqual(result, { category: 'primary', source: 'triage-category' });
  });

  test('default is primary', () => {
    assert.deepEqual(classifyCategory({ fromDomain: 'someone.example.com' }), {
      category: 'primary',
      source: 'default',
    });
  });

  test('headerless backfill (bulkSignals null) still uses domain / triage', () => {
    const social = classifyCategory({
      fromDomain: 'reddit.com',
      bulkSignals: null,
    });
    assert.deepEqual(social, { category: 'social', source: 'social-domain' });

    const newsletter = classifyCategory({
      fromDomain: 'brand.example.com',
      bulkSignals: null,
      triage: { category: 'notification' },
    });
    assert.deepEqual(newsletter, { category: 'other', source: 'triage-category' });
  });
});

describe('rollupThreadCategory', () => {
  test('primary wins over social and other', () => {
    assert.equal(rollupThreadCategory(['other', 'social', 'primary']), 'primary');
    assert.equal(rollupThreadCategory(['other', 'social']), 'social');
    assert.equal(rollupThreadCategory(['other']), 'other');
    assert.equal(rollupThreadCategory([]), '');
  });
});
